config/routes.rb
Peng::Application.routes.draw do

  get "admin/index", :as => 'index'
  match "admin/login", :as => 'login'
  get "admin/logout", :as => 'logout'

  get "admin/init_admin"

  resources :sales do
    collection do
      get "list_admin"
      get "list_month"
      get "list_summary"
    end
  end

  resources :users

  resources :stores

  root :to => "admin#login"

end

app/models/store.rb
# -*- encoding : utf-8 -*-
class Store < ActiveRecord::Base
  has_many :users
  has_many :sales

  validates_presence_of :name, :message => "店铺名不允许为空"
end

app/controllers/stores_controller.rb
# -*- encoding : utf-8 -*-
class StoresController < ApplicationController
  load_and_authorize_resource
  # GET /stores
  # GET /stores.xml
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.xml
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.xml
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.xml
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to(store_path(@store), :notice => 'Store was successfully created.') }
        format.xml  { render :xml => @store, :status => :created, :location => @store }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @store.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.xml
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to(store_path(@store), :notice => 'Store was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @store.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.xml
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to(stores_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stores_helper.rb
# -*- encoding : utf-8 -*-
module StoresHelper
end

app/views/stores/_form.html.erb
  <div class="group">
    <%= f.label :name, "店铺名", :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">必填</span>
  </div>

  <div class="group">
    <%= f.label :other, "备注", :class => :label %>
    <%= f.text_field :other, :class => 'text_field' %>
    <span class="description">可不填</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "保存") %> 保存
  </button>
  <span class="text_button_padding">或</span>
	<%= link_to "取消", stores_path, :class => "text_button_padding link_button" %>
</div>

app/views/stores/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "列表", stores_path  %></li>
      <li><%= link_to "添加", new_store_path %></li>
      <li class="active"><%= link_to "编辑", edit_store_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">编辑门店</h2>
    <div class="inner">
      <%= form_for @store, :url => store_path(@store), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "列表", stores_path  %></li>
      <li><%= link_to "添加", new_store_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">所有门店</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            店铺名
          </th>
                    <th>添加时间</th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @stores.each do |store| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= store.id %>
          </td>
                    <td>
            <%= link_to store.name, store_path(store) %>
          </td>
                    <td>
            <%= store.created_at %>
          </td>
          <td class="last">
            <%= link_to "查看", store_path(store) %> |
            <%= link_to "编辑", edit_store_path(store) %> |
            <%= link_to "删除", store_path(store), :method => :delete, :confirm => "确认删除吗?" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        
      </div>
    </div>
  </div>
</div>

app/views/stores/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "列表", stores_path  %></li>
      <li class="active"><%= link_to "添加", new_store_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">添加门店</h2>
    <div class="inner">
      <%= form_for :store, :url => stores_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "列表", stores_path  %></li>
      <li><%= link_to "添加", new_store_path %></li>
      <li class="active"><%= link_to "查看", store_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b>店铺名:</b>
          <%= @store.name %>
        </p>

        <p>
          <b>备注:</b>
          <%= @store.other %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "编辑") + " " + "编辑", edit_store_path(@store), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "删除") + " " + "删除", store_path(@store), :method => "delete", :class => "button", :confirm => "确认删除吗?" %>
      </div>      
    </div>
  </div>
</div>