config/routes.rb
Peng::Application.routes.draw do

  get "admin/index", :as => 'index'
  match "admin/login", :as => 'login'
  get "admin/logout", :as => 'logout'

  get "admin/init_admin"

  resources :sales do
    collection do
      get "list_admin"
      get "list_month"
      get "list_summary"
    end
  end

  resources :users

  resources :stores

  root :to => "admin#login"

end

app/models/sale.rb
# -*- encoding : utf-8 -*-
class Sale < ActiveRecord::Base
  belongs_to :store
  belongs_to :user

  SALE_TYPE = [["外销",1],["内销",2]]

  validates_numericality_of :inlay, :pearl,:pt,:gold,:kgold, :hard_gold, :other, :old_gold, :old_pt, :gold_jade, :color_stone, :message => "营业额不能为空且要大于或等于0的数字,支持小数", :greater_than_or_equal_to => 0
  validate :valid_sale_time
  validate :valid_data_uni, :on => :create

  before_save :sum_day

  def new_material_sum
    inlay + pearl + kgold + pt + hard_gold + gold + other + gold_jade + color_stone
  end

  def old_material_sum
    old_gold + old_pt
  end

  protected
  def sum_day
    self.day = self.inlay + self.pearl + self.pt + self.hard_gold + self.gold + self.kgold + self.other + self.old_gold + self.old_pt + self.color_stone + self.gold_jade
  end

  private
  def valid_sale_time
    if sale_time > Date.current || sale_time < (Date.current - 31)
      errors.add(:sate_time,"日期必须要小于或等于今天,且只能录入前31天以内的数据")
    end
  end

  def valid_data_uni
    if Sale.count(:all,:conditions => ["store_id = ? and sale_type = ? and sale_time = ?",store_id,sale_type,sale_time]) > 0
      errors.add_to_base "每个店铺每种数据类型每天只能录入一条"
    end
  end

end

app/controllers/sales_controller.rb
# -*- encoding : utf-8 -*-
class SalesController < ApplicationController
  load_and_authorize_resource

  # GET /sales
  # GET /sales.xml
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.xml
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.xml
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.xml
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @current_user.role? :employee
        @sale.user = @current_user
        @sale.store_id = @current_user.store_id
        if @sale.save
          format.html { redirect_to(list_month_sales_path, :notice => '添加成功') }
          format.xml { render :xml => @sale, :status => :created, :location => @sale }
        else
          format.html { render :action => "new" }
          format.xml { render :xml => @sale.errors, :status => :unprocessable_entity }
        end
      else
        @sale.errors.add_to_base '请用雇员帐号登陆进行此操作'
        format.html { render :action => "new" }
        format.xml { render :xml => @sale.errors, :status => :unprocessable_entity }
      end

    end
  end

  # PUT /sales/1
  # PUT /sales/1.xml
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to(sale_path(@sale), :notice => '更新成功.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.xml
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to(list_admin_sales_path) }
      format.xml { head :ok }
    end
  end

  def list_month
    @current_date = Date.current
    @current_date = @current_date.prev_month if params[:month] == "prev"
    @sales = Sale.find(:all,
                       :conditions => ["store_id=? and sale_time>=? and sale_time<=?", current_user.store_id, @current_date.beginning_of_month, @current_date.end_of_month],
                       :order => "sale_time asc")
    sum_data
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @sales }
    end
  end

  def list_admin
    @current_date = Date.current
    @current_date = Date.new(params[:date][:year].to_i, params[:date][:month].to_i, 1) unless params[:date].nil?
    if params[:store_id].nil?
      @store_id = Store.all().first.id
    else
      @store_id = params[:store_id]
    end
    @sales = Sale.find(:all, :conditions => ["store_id=? and sale_time>=? and sale_time<=?", @store_id, @current_date.beginning_of_month, @current_date.end_of_month],
                       :order => "sale_type asc,sale_time asc")

    if params[:commit].nil? or params[:commit] == "查询"
      sum_data
      respond_to do |format|
        format.html
        format.xml { render :xml => @sales }
      end
    elsif params[:commit] == "导出"
      render :layout=>nil,:file => "#{Rails.root}/public/403.html", :status => 403 and return unless current_user.admin?
      send_file(export_write_data(@sales, Store.find(@store_id), @current_date))
    end

  end

  def list_summary
    @current_date = Date.current
    @current_date = Date.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i) unless params[:date].nil?

    #外销
    str_sql_cols = "store_id AS store_id, SUM(pt) AS pt, SUM(gold) AS gold, SUM(gold_jade) AS gold_jade, SUM(color_stone) AS color_stone, SUM(inlay) AS inlay, SUM(kgold) AS kgold, SUM(other) AS other, SUM(old_gold) AS old_gold, SUM(old_pt) AS old_pt, SUM(pearl) AS pearl, SUM(hard_gold) as hard_gold, SUM(day) AS day "
    @sum_days = Sale.group("store_id").where(:sale_time => @current_date, :sale_type => 1).select(str_sql_cols)
    @sum_months = Sale.group("store_id").where(:sale_time => @current_date.beginning_of_month..@current_date.end_of_month, :sale_type => 1).select(str_sql_cols)
    @sum_years = Sale.group("store_id").where(:sale_time => @current_date.beginning_of_year..@current_date.end_of_year, :sale_type => 1).select(str_sql_cols)

    #内销
    @sum_days2 = Sale.group("store_id").where(:sale_time => @current_date, :sale_type => 2).select(str_sql_cols)
    @sum_months2 = Sale.group("store_id").where(:sale_time => @current_date.beginning_of_month..@current_date.end_of_month, :sale_type => 2).select(str_sql_cols)
    @sum_years2 = Sale.group("store_id").where(:sale_time => @current_date.beginning_of_year..@current_date.end_of_year, :sale_type => 2).select(str_sql_cols)

    @stores = Store.all
  end

  private
  def sum_data
    @month_sum = @inlay_sum = @pearl_sum = @pt_sum = @hard_gold_sum = @gold_sum = @kgold_sum = @other_sum = @old_gold_sum = @old_pt_sum  = @gold_jade_sum = @color_stone_sum = 0
    msales = @sales.select { |ms| ms.sale_type == 1 } #外销
    msales.each do |msale|
    unless msale.nil?
      @month_sum += msale.day
      @inlay_sum += msale.inlay
        @pearl_sum += msale.pearl
        @pt_sum += msale.pt
        @hard_gold_sum += msale.hard_gold
        @gold_sum += msale.gold
        @kgold_sum += msale.kgold
        @other_sum += msale.other
        @old_gold_sum += msale.old_gold
        @old_pt_sum += msale.old_pt
        @gold_jade_sum += msale.gold_jade
        @color_stone_sum += msale.color_stone
      end
    end
    @new_material_month_sum = @inlay_sum + @pearl_sum + @pt_sum + @hard_gold_sum + @gold_sum + @kgold_sum + @other_sum + @gold_jade_sum + @color_stone_sum
    @old_material_month_sum = @old_gold_sum + @old_pt_sum

    @month_sum2 = @inlay_sum2 = @pearl_sum2 = @pt_sum2 = @hard_gold_sum2 = @gold_sum2 = @kgold_sum2 = @other_sum2 = @old_gold_sum2 = @old_pt_sum2 = @gold_jade_sum2 = @color_stone_sum2 = 0
    msales = @sales.select { |ms| ms.sale_type == 2 } #内销
    msales.each do |msale|
      unless msale.nil?
        @month_sum2 += msale.day
        @inlay_sum2 += msale.inlay
        @pearl_sum2 += msale.pearl
        @pt_sum2 += msale.pt
        @hard_gold_sum2 += msale.hard_gold
        @gold_sum2 += msale.gold
        @kgold_sum2 += msale.kgold
        @other_sum2 += msale.other
        @old_gold_sum2 += msale.old_gold
        @old_pt_sum2 += msale.old_pt
        @gold_jade_sum2 += msale.gold_jade
        @color_stone_sum2 += msale.color_stone
      end
    end
    @new_material_month_sum2 = @inlay_sum2 + @pearl_sum2 + @pt_sum2 + @hard_gold_sum2 + @gold_sum2 + @kgold_sum2 + @other_sum2 + @gold_jade_sum2 + @color_stone_sum2
    @old_material_month_sum2 = @old_gold_sum2 + @old_pt_sum2
  end

  def export_write_data(sales_data, store, export_date)
    Spreadsheet.client_encoding = 'UTF-8'

    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet

    sheet1.name = "#{store.name}_#{export_date.to_s[0..-4]}"

#header
    sheet1.row(0).insert 0, "日期", "星期", "(#{store.name}) 店"
    sheet1.row(1).insert 2, *['钻石', '珍珠', '铂金', '硬金', '黄金', '金镶玉', '彩宝', 'K金', '其它', '合计', '黄金旧料', '铂金旧料', '旧料合计','当天合计', '本月累计']
    sheet1.row(2).insert 2, *%w{营业额 营业额 营业额 营业额 营业额 营业额 营业额 营业额 营业额}

#data
    month_sum = inlay_sum = pearl_sum = hard_gold_sum = pt_sum = gold_sum = kgold_sum = other_sum = old_gold_sum = old_pt_sum = gold_jade_sum = color_stone_sum = 0
    month_sum2 = inlay_sum2 = pearl_sum2 = hard_gold_sum2 = pt_sum2 = gold_sum2 = kgold_sum2 = other_sum2 = old_gold_sum2 = old_pt_sum2 = gold_jade_sum2 = color_stone_sum2 = 0
    (export_date.beginning_of_month.day.to_i..export_date.end_of_month.day).each do |mday|
      mdate = export_date.change(:day=>mday)
      week = ["日", "一", "二", "三", "四", "五", "六"][mdate.wday]
      row_data = sheet1.row(mday+2)
      row_data.insert 0, *[mday, week]
      msale = sales_data.find { |ms| ms.sale_time == mdate and ms.sale_type == 1 } #外销
      unless msale.nil?
        month_sum += msale.day
        inlay_sum += msale.inlay
        pearl_sum += msale.pearl
        hard_gold_sum += msale.hard_gold
        pt_sum += msale.pt
        gold_sum += msale.gold
        gold_jade_sum += msale.gold_jade
        color_stone_sum += msale.color_stone
        kgold_sum += msale.kgold
        other_sum += msale.other
        old_gold_sum += msale.old_gold
        old_pt_sum += msale.old_pt
        row_data.insert 2, msale.inlay, msale.pearl, msale.pt, msale.hard_gold, msale.gold, msale.gold_jade, msale.color_stone, msale.kgold, msale.other, (msale.inlay + msale.pearl + msale.pt + msale.hard_gold + msale.gold + msale.kgold + msale.other), msale.old_gold, msale.old_pt, (msale.old_gold + msale.old_pt), msale.day, month_sum
      end
      msale = sales_data.find { |ms| ms.sale_time == mdate and ms.sale_type == 2 } #内销
      unless msale.nil?
        month_sum2 += msale.day
        inlay_sum2 += msale.inlay
        pearl_sum2 += msale.pearl
        hard_gold_sum2 += msale.hard_gold
        pt_sum2 += msale.pt
        gold_sum2 += msale.gold
        gold_jade_sum2 += msale.gold_jade
        color_stone_sum2 += msale.color_stone
        kgold_sum2 += msale.kgold
        other_sum2 += msale.other
        old_gold_sum2 += msale.old_gold
        old_pt_sum2 += msale.old_pt
      end

    end

    #footer
    i = 1
    sheet1.row(3+export_date.end_of_month.day).insert(0, "商场合计")
    sheet1.row(3+export_date.end_of_month.day).insert(i+=1, inlay_sum)
    sheet1.row(3+export_date.end_of_month.day).insert(i+=1, pearl_sum)
    sheet1.row(3+export_date.end_of_month.day).insert(i+=1, pt_sum)

app/helpers/sales_helper.rb
# -*- encoding : utf-8 -*-
module SalesHelper
  def get_type(type_value)
    sale_type = Sale::SALE_TYPE
    sale_type = sale_type.map { |t|t.reverse}
    Hash[*sale_type.flatten][type_value]
  end

  def select_store_all
    stores = Store.all.map { |u| [u.name,u.id]}
    stores.insert(0,['请选择',''])
  end

  def select_store_all_admin
    stores = Store.all.map { |u| [u.name,u.id]}
  end
end

app/views/sales/_footer_sum.html.erb
        <% if !@sales.blank? %>
        总共:<%= @sales.length %> 条 | 外销:<%= @sales.select { |s| s.sale_type == 1 }.length %> 条 |
        内销:<%= @sales.select { |s| s.sale_type == 2 }.length %> 条 <br/>
        外销统计: 钻石 <%= @inlay_sum %>  | 珍珠 <%= @pearl_sum %>  | 铂金 <%= @pt_sum %>   |  硬金 <%= @hard_gold_sum %>  | 黄金 <%= @gold_sum %>  | K金 <%= @kgold_sum %>  | 
        金镶玉 <%= @gold_jade_sum %> | 彩宝 <%= @color_stone_sum %> | 其它 <%= @other_sum %> | 合计 <%= @new_material_month_sum %> | 
         黄金旧料 <%= @old_gold_sum %> | 铂金旧料 <%= @old_pt_sum %> | 旧料合计 <%= @old_material_month_sum %> | 总计 <%= @month_sum %> <br/>
         内销统计: 钻石 <%= @inlay_sum2 %>  |  珍珠 <%= @pearl_sum2 %>  | 铂金 <%= @pt_sum2 %>  |  硬金 <%= @hard_gold_sum2 %>  | 黄金 <%= @gold_sum2 %>  |
        K金 <%= @kgold_sum2 %>  | 金镶玉 <%= @gold_jade_sum2 %> | 彩宝 <%= @color_stone_sum2 %> | 其它 <%= @other_sum2 %> | 合计 <%= @new_material_month_sum2 %>  | 黄金旧料 <%= @old_gold_sum2 %> | 铂金旧料 <%= @old_pt_sum2 %> | 旧料合计 <%= @old_material_month_sum2 %>  | 总计 <%= @month_sum2 %>
        <% end %>

app/views/sales/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "列表", :action => :list_admin  %></li>
      <li class="active"><%= link_to "编辑", edit_sale_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">编辑营销额</h2>
    <div class="inner">
      <%= form_for @sale, :url => sale_path(@sale), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/sales/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", sales_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_sale_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Sales</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.sale.sale_type", :default => t("activerecord.labels.sale_type", :default => "Sale_type")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @sales.each do |sale| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= sale.id %>
          </td>
                    <td>
            <%= link_to sale.sale_type, sale_path(sale) %>
          </td>
                    <td>
            <%= sale.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", sale_path(sale) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_sale_path(sale) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", sale_path(sale), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @sales  %>
        
      </div>
    </div>
  </div>
</div>

app/views/sales/list_admin.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "汇总", :action => :list_summary %></li>
      <li class="active"><%= link_to "列表", :action => :list_admin %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= "#{@current_date.year}年#{@current_date.month}月 #{Store.find(@store_id).name}  营业额数据" %></h2>
    <%= form_tag({:action => :list_admin}, :method => "get") do %>
        <div style="margin-left: 15px;margin-bottom:10px;">门店: <%= select_tag(:store_id, options_for_select(select_store_all_admin, @store_id)) %>
          日期: <%= select_year(@current_date) %>年
          <%= select_month(@current_date, :use_month_numbers => true) %>月 <%= submit_tag "查询" %>
          <% if session[:current_user].role? :admin %> <%= submit_tag "导出" %>
          <% end %>
        </div>
    <% end %>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>日期</th>
          <th>钻石</th>
          <th>珍珠</th>
          <th>K金</th>
          <th>铂金</th>
          <th>硬金</th>
          <th>黄金</th>
          <th>金镶玉</th>
          <th>彩宝</th>
          <th>其它</th>
          <th>合计</th>
          <th>黄金旧料</th>
          <th>铂金旧料</th>
          <th>旧料合计</th>
          <th>类 型</th>
          <th>当天总额</th>
          <th></th>
        </tr>
        <% @sales.each do |sale| -%>
            <tr class="<%= cycle("odd", "even") %>">
              <td><%= sale.id %></td>
              <td><%= sale.sale_time %></td>
              <td><%= sale.inlay %></td>
              <td><%= sale.pearl %></td>
              <td><%= sale.kgold %></td>
              <td><%= sale.pt %></td>
              <td><%= sale.hard_gold %></td>
              <td><%= sale.gold %></td>
              <td><%= sale.gold_jade %></td>
              <td><%= sale.color_stone %></td>
              <td><%= sale.other %></td>
              <td><%= sale.new_material_sum %></td>
              <td><%= sale.old_gold %></td>
              <td><%= sale.old_pt %></td>
              <td><%= sale.old_material_sum %></td>
              <td><%= get_type sale.sale_type %></td>
              <td>
                <%= sale.day %>
              </td>
              <td class="last">
                <%= link_to '查看', sale %> |
                <%= link_to '编辑', edit_sale_path(sale) %> |
                <%= link_to '删除', sale, :confirm => '确认删除吗?', :method => :delete %>
              </td>
            </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf" style="text-align:right;">
        <%= render :partial => "footer_sum" %>
      </div>
    </div>
  </div>
</div>

app/views/sales/list_month.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <% if @current_date.month==Date.current.month %>
      <li class="first active"><%= link_to "查看当月", :action => :list_month  %></li>
      <li><%= link_to "查看上月", :action => :list_month,:month=>"prev" %></li>
      <% else %>
       <li class="first"><%= link_to "查看当月", :action => :list_month  %></li>
      <li class="active"><%= link_to "查看上月", :action => :list_month,:month=>"prev" %></li>
      <% end %>
      <li><%= link_to "添加", new_sale_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= "#{@current_date.year}年#{@current_date.month}月 #{@current_user.store.name} 营业额数据" %></h2>
    <div class="inner">
      <table class="table">
       <tr>
         <th class="first">ID</th>
         <th>日 期</th>
         <th>钻石</th>
         <th>珍珠</th>
         <th>K 金</th>
         <th>铂金</th>
         <th>硬金</th>
         <th>黄金</th>
         <th>金镶玉</th>
         <th>彩宝</th>
         <th>其它</th>
         <th>黄金旧料</th>
         <th>铂金旧料</th>
         <th>类型</th>
         <th class="last">当天总额</th>
       </tr>
       <% @sales.each do |sale| -%>
       <tr class="<%= cycle("odd", "even") %>">
         <td><%= sale.id %></td>
         <td><%= sale.sale_time %></td>
         <td><%= sale.inlay %></td>
         <td><%= sale.pearl %></td>
         <td><%= sale.kgold %></td>
         <td><%= sale.pt %></td>
         <td><%= sale.hard_gold %></td>
         <td><%= sale.gold %></td>
         <td><%= sale.gold_jade %></td>
         <td><%= sale.color_stone %></td>
         <td><%= sale.other %></td>
         <td><%= sale.old_gold %></td>
         <td><%= sale.old_pt %></td>
         <td><%= get_type sale.sale_type %></td>
         <td class="last">
           <%= sale.day %>
         </td>
       </tr>
       <% end -%>
      </table>
      <div class="actions-bar wat-cf" style="text-align:right;">
        <%= render :partial => "footer_sum" %>
      </div>
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "查看", :action => :list_month  %></li>
      <li class="active"><%= link_to "添加", new_sale_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">添加营业额数据</h2>
    <div class="inner">
      <%= form_for :sale, :url => sales_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/sales/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "列表", :action => :list_admin %></li>
      <li class="active"><%= link_to "查看", sale_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">

      <p>
        <b>类型:</b>
        <%= Sale::SALE_TYPE.rassoc(@sale.sale_type)[0] %>
      </p>

      <p>
        <b>钻石:</b>
        <%= @sale.inlay %>
      </p>

      <p>
        <b>珍珠:</b>
        <%= @sale.pearl %>
      </p>

      <p>
        <b>铂金:</b>
        <%= @sale.pt %>
      </p>

      <p>
        <b>硬金:</b>
        <%= @sale.hard_gold %>
      </p>

      <p>
        <b>黄金:</b>
        <%= @sale.gold %>
      </p>

      <p>
        <b>K金:</b>
        <%= @sale.kgold %>
      </p>

      <p>
        <b>金镶玉</b>
        <%= @sale.gold_jade %>
      </p>

      <p>
        <b>彩宝</b>
        <%= @sale.color_stone %>
      </p>

      <p>
        <b>其它</b>
        <%= @sale.other %>
      </p>

      <p>
        <b>黄金旧料</b>
        <%= @sale.old_gold %>
      </p>

      <p>
        <b>铂金旧料</b>
        <%= @sale.old_pt %>
      </p>

      <p>
        <b>当天总计:</b>
        <%= @sale.day %>
      </p>

      <p>
        <b>销售时间:</b>
        <%= @sale.sale_time %>
      </p>

      <p>
        <b>门店:</b>
        <%= @sale.store.name %>
      </p>

      <p>
        <b>用户:</b>
        <%= @sale.user.username %>
      </p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "编辑") + " " + "编辑", edit_sale_path(@sale), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "删除") + " " + "删除", sale_path(@sale), :method => "delete", :class => "button", :confirm => "确认删除吗?" %>
      </div>
    </div>
  </div>
</div>